#!/usr/bin/env python3
"""
opencode_engine.py — OpenCode engine generator (OpenCode v2).

Reads .kilo/ (source of truth) and emits .opencode/ (agents, commands,
instructions) plus root opencode.json targeting the OpenCode **v2** schema.

History:
  .opencode/ was removed in v4.0.0, reintroduced in v4.2.0 for OpenCode v1.18.
  v1.18 shipped as npm `opencode-ai`; the v2 line ships as `@opencode/cli`
  (verified 2026-09-27: `opencode-ai` latest = 1.18.32, `@opencode/cli`
  latest = 2.0.18, plugin SDK `@opencode-ai/plugin` -> `@opencode/plugin`).
  The v2 config surface is not backward compatible, so this engine now emits
  v2 shapes only. See opencode.ai/v2/docs/{config,permissions,agents,providers,
  instructions}.

Transform rules (source -> OpenCode v2):
  - agents:   .kilo/agents/*.md   -> .opencode/agents/*.md
              Kilo's `permission:` object is rewritten to v2's ordered
              `permissions:` array. `bash` -> `shell`, `task` -> `subagent`,
              and `codesearch`/`mcp` are dropped (no v2 action). Within a
              permission map the exact `*` rule is emitted first so the more
              specific rules follow it: v2 resolves with last-match-wins,
              while Kilo resolves the most specific match.
  - commands: .kilo/command/*.md  -> .opencode/commands/*.md (verbatim)
  - skills:   NOT mirrored. OpenCode v2 loads `.opencode/skills/` AND the
              Claude-compatible `.claude/skills/` and `.agents/skills/`
              (docs: Skills > Discovery). Mirroring .kilo/skill into a second
              location would register every skill twice, so OpenCode relies on
              `.claude/skills/` (generated by claude_engine) and this engine
              prunes any legacy `.opencode/skills/` mirror.
              Skills whose frontmatter sets `disable-model-invocation: true`
              become `permission.skill[name] = "ask"` in opencode.json, since
              OpenCode ignores that Claude-only field (see collect_disabled_skills).
  - instructions: OpenCode v2 accepts an `instructions` config array but does
              not resolve it, and loads only `AGENTS.md` (docs: Instructions >
              Configuration). The `.kilo/instruction/*.md` bodies are therefore
              inlined into the root `AGENTS.md` between markers, and any legacy
              `.opencode/instruction/` mirror is pruned.
  - config:   root opencode.json is emitted in the v2 schema: `agents` and
              `providers` (plural), an ordered `permissions` array, and a
              self-contained `commandcode` provider replacing the retired v1
              plugin `commandcode-go-opencode-provider`. Only the
              `commandcode/<id>` models the harness references are declared
              (_PROVIDER_MODELS); add an entry there when a new reference lands.
"""

from __future__ import annotations

import contextlib
import json
import re
import shutil
from pathlib import Path
from typing import Any

TOOLS_DIR = Path(__file__).resolve().parent
ROOT_DIR = TOOLS_DIR.parent

# Kilo permission keys with no OpenCode v2 equivalent tool.
_DROP_PERMISSION_KEYS = {"codesearch", "mcp"}

# Kilo permission keys renamed in OpenCode v2 (docs: Permissions > Configure).
_PERMISSION_ACTION_RENAME = {"bash": "shell", "task": "subagent"}

# OpenCode-side action for skills whose Kilo/Claude frontmatter sets
# `disable-model-invocation: true`. OpenCode ignores that field and has no
# user-only skill invocation, so "ask" is the closest faithful mapping: the
# model may request the skill, but the user approves before it loads.
_DISABLED_SKILL_PERMISSION = "ask"

# Markers delimiting the generated instruction block inside the root AGENTS.md.
_AGENTS_MARKER_BEGIN = (
    "<!-- BEGIN opencode-v2-inline-instructions "
    "(generated from .kilo/instruction/*.md by tools/opencode_engine.py) -->"
)
_AGENTS_MARKER_END = "<!-- END opencode-v2-inline-instructions -->"

# Models the harness references, declared explicitly because the v2 provider is
# self-contained and no longer inherits the retired v1 plugin's catalog. The key
# is the harness-facing `commandcode/<key>` id; `modelID` is the upstream
# Command Code catalog id (verified via GET {COMMANDCODE_BASE_URL}/models,
# 2026-09-27). Only referenced models are declared -- add one here when a new
# `commandcode/<id>` reference is introduced.
_PROVIDER_ID = "commandcode"
_DEFAULT_MODEL = "commandcode/deepseek-v4-pro"
_SMALL_MODEL = "commandcode/gpt-5.4-mini"
_PROVIDER_MODELS: dict[str, dict[str, Any]] = {
    "deepseek-v4-pro": {
        "modelID": "deepseek/deepseek-v4-pro",
        "name": "DeepSeek V4 Pro",
        "limit": {"context": 1000000, "output": 384000},
    },
    "deepseek-v4-flash": {
        "modelID": "deepseek/deepseek-v4-flash",
        "name": "DeepSeek V4 Flash",
        "limit": {"context": 1000000, "output": 384000},
    },
    "deepseek-v4.1-flash": {
        "modelID": "deepseek/deepseek-v4.1-flash",
        "name": "DeepSeek V4.1 Flash",
        "limit": {"context": 1000000, "output": 384000},
    },
    "gpt-5.4-mini": {
        "modelID": "gpt-5.4-mini",
        "name": "GPT-5.4 Mini",
        "limit": {"context": 400000, "output": 128000},
    },
    "glm-5": {
        "modelID": "zai-org/GLM-5",
        "name": "GLM-5",
        "limit": {"context": 200000, "output": 131072},
    },
    "glm-5.1": {
        "modelID": "zai-org/GLM-5.1",
        "name": "GLM-5.1",
        "limit": {"context": 200000, "output": 131072},
    },
    "qwen3.7-max": {
        "modelID": "Qwen/Qwen3.7-Max",
        "name": "Qwen 3.7 Max",
        "limit": {"context": 1000000, "output": 131072},
    },
    "qwen3.6-plus": {
        "modelID": "Qwen/Qwen3.6-Plus",
        "name": "Qwen 3.6 Plus",
        "limit": {"context": 1000000, "output": 131072},
    },
}

# Ordered allow/deny rules guarding destructive shell use. v2 resolves with
# last-match-wins, so broad rules precede specific allow/deny rules.
_BASE_PERMISSION_RULES: list[dict[str, str]] = [
    {"action": "edit", "resource": "*", "effect": "ask"},
    {"action": "external_directory", "resource": "*", "effect": "ask"},
    {"action": "shell", "resource": "*", "effect": "ask"},
    {"action": "shell", "resource": "python .github/scripts/security_scan.py *", "effect": "allow"},
    {"action": "shell", "resource": "python .github/scripts/checklist.py *", "effect": "allow"},
    {"action": "shell", "resource": "git status *", "effect": "allow"},
    {"action": "shell", "resource": "git diff *", "effect": "allow"},
    {"action": "shell", "resource": "git log *", "effect": "allow"},
    {"action": "shell", "resource": "git add *", "effect": "allow"},
    {"action": "shell", "resource": "git commit *", "effect": "allow"},
    {"action": "shell", "resource": "git push *", "effect": "ask"},
    {"action": "shell", "resource": "git reset --hard *", "effect": "deny"},
    {"action": "shell", "resource": "git push --force *", "effect": "deny"},
    {"action": "shell", "resource": "rm -rf *", "effect": "deny"},
    {"action": "shell", "resource": "del /s /q *", "effect": "deny"},
    {"action": "shell", "resource": "DROP TABLE *", "effect": "deny"},
    {"action": "shell", "resource": "DROP DATABASE *", "effect": "deny"},
]


def _write_if_changed(path: Path, content: str) -> None:
    """Write `content` as LF text, but only when it differs from what is there.

    An unconditional write bumps mtime, and `git status` then reports every
    generated artifact as modified while `git diff` shows nothing at all -- it
    compares stat first and only reads content on `git diff`. Mirrors the guard
    in claude_engine._write_lf.
    """
    if path.exists():
        with contextlib.suppress(OSError, UnicodeDecodeError):
            if path.read_text(encoding="utf-8") == content:
                return
    path.write_text(content, encoding="utf-8", newline="")


def _copy_if_changed(src: Path, dst: Path) -> None:
    """Copy `src` over `dst` only when the bytes actually differ."""
    data = src.read_bytes()
    if dst.exists():
        with contextlib.suppress(OSError):
            if dst.read_bytes() == data:
                return
    dst.write_bytes(data)


def _frontmatter_block(text: str) -> str | None:
    """Return the text between the opening and closing `---` fences, or None."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    return text[3:end]


def collect_disabled_skills(kilo_root: Path) -> dict[str, str]:
    """Map skill name -> permission action for skills marked
    `disable-model-invocation: true` in .kilo/skill/<name>/SKILL.md.
    """
    out: dict[str, str] = {}
    skill_root = kilo_root / "skill"
    if not skill_root.is_dir():
        return out
    for skill_dir in sorted(p for p in skill_root.iterdir() if p.is_dir()):
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            continue
        fm = _frontmatter_block(skill_md.read_text(encoding="utf-8"))
        if fm is None:
            continue
        for line in fm.splitlines():
            key, _, value = line.partition(":")
            if key.strip() == "disable-model-invocation" and value.strip().lower() == "true":
                out[skill_dir.name] = _DISABLED_SKILL_PERMISSION
                break
    return out


def _parse_permission_block(frontmatter: str) -> tuple[list[str], list[tuple[str, list[tuple[str, str]]]]]:
    """Split an agent frontmatter into (kept lines, permission entries).

    `kept lines` are every frontmatter line outside the `permission:` block,
    preserved verbatim and in order. `permission entries` are ordered
    (action, [(resource, effect), ...]) pairs; a scalar permission such as
    `edit: allow` becomes a single `("*", "allow")` rule.
    """
    kept: list[str] = []
    entries: list[tuple[str, list[tuple[str, str]]]] = []
    lines = frontmatter.split("\n")
    i = 0
    while i < len(lines):
        raw = lines[i]
        if raw.strip() != "permission:":
            kept.append(raw)
            i += 1
            continue

        # Collect the permission block's child lines until the next dedent.
        children: list[tuple[int, str, str | None]] = []
        i += 1
        while i < len(lines):
            nxt = lines[i]
            if not nxt.strip():
                i += 1
                continue
            indent = len(nxt) - len(nxt.lstrip(" "))
            if indent == 0:
                break
            key, sep, value = nxt.strip().partition(":")
            key = key.strip().strip('"').strip("'")
            children.append((indent, key, value.strip() if sep else None))
            i += 1

        idx = 0
        while idx < len(children):
            indent, key, value = children[idx]
            if value:
                entries.append((key, [("*", value)]))
                idx += 1
                continue
            rules: list[tuple[str, str]] = []
            idx += 1
            while idx < len(children) and children[idx][0] > indent:
                _, resource, effect = children[idx]
                rules.append((resource, effect or ""))
                idx += 1
            entries.append((key, rules))

    while kept and not kept[-1].strip():
        kept.pop()
    return kept, entries


def _render_permissions(entries: list[tuple[str, list[tuple[str, str]]]]) -> list[str]:
    """Render permission entries as a v2 `permissions:` YAML block sequence.

    The exact `*` rule is emitted before the rest so specific rules win under
    v2's last-match-wins resolution.
    """
    rules: list[tuple[str, str, str]] = []
    for action, children in entries:
        if action in _DROP_PERMISSION_KEYS:
            continue
        mapped = _PERMISSION_ACTION_RENAME.get(action, action)
        ordered = [c for c in children if c[0] == "*"] + [c for c in children if c[0] != "*"]
        for resource, effect in ordered:
            if not effect:
                continue
            rules.append((mapped, resource, effect))
    if not rules:
        return []
    out = ["permissions:"]
    for action, resource, effect in rules:
        out.append(f"  - action: {action}")
        out.append(f'    resource: "{resource}"')
        out.append(f"    effect: {effect}")
    return out


def _convert_agent_frontmatter(frontmatter: str) -> str:
    kept, entries = _parse_permission_block(frontmatter)
    rendered = kept + _render_permissions(entries)
    return "\n".join(rendered).rstrip("\n")


def generate_agents(kilo_root: Path, opencode_root: Path) -> int:
    src_dir = kilo_root / "agents"
    dst_dir = opencode_root / "agents"
    if not src_dir.is_dir():
        print(f"[ERROR] Source agent directory not found: {src_dir}")
        return 1
    dst_dir.mkdir(parents=True, exist_ok=True)
    copied = 0
    for agent_file in sorted(src_dir.glob("*.md")):
        content = agent_file.read_text(encoding="utf-8")
        split = content.split("---", 2)
        if len(split) < 3:
            print(f"  [SKIP] agents/{agent_file.name} (no frontmatter)")
            continue
        fm = _convert_agent_frontmatter(split[1].strip("\n"))
        body = split[2].lstrip("\n")
        new_content = f"---\n{fm}\n---\n{body}"
        _write_if_changed(dst_dir / agent_file.name, new_content)
        copied += 1
        print(f"  [GEN] agents/{agent_file.name}")
    print(f"OpenCode agents generated: {copied}")
    return 0


def generate_commands(kilo_root: Path, opencode_root: Path) -> int:
    src_dir = kilo_root / "command"
    dst_dir = opencode_root / "commands"
    if not src_dir.is_dir():
        print(f"[ERROR] Source command directory not found: {src_dir}")
        return 1
    dst_dir.mkdir(parents=True, exist_ok=True)
    copied = 0
    for cmd_file in sorted(src_dir.glob("*.md")):
        content = cmd_file.read_text(encoding="utf-8")
        _write_if_changed(dst_dir / cmd_file.name, content)
        copied += 1
        print(f"  [GEN] commands/{cmd_file.name}")
    print(f"OpenCode commands generated: {copied}")
    return 0


def prune_duplicate_skills(opencode_root: Path) -> int:
    """Remove `.opencode/skills/` if a legacy mirror is present.

    OpenCode v2 loads `.opencode/skills/`, the Claude-compatible
    `.claude/skills/`, and `.agents/skills/`. Mirroring .kilo/skill into
    `.opencode/skills/` while `.claude/skills/` already carries the same IDs
    registers every skill twice, so OpenCode relies on `.claude/skills/` alone.
    This deletes the redundant mirror left behind by older harness versions.
    """
    dst = opencode_root / "skills"
    if dst.exists():
        shutil.rmtree(dst)
        print("  [PRUNE] skills/ (duplicate of .claude/skills — removed)")
        return 1
    print("  [OK] skills/ absent (OpenCode reads .claude/skills/)")
    return 0


def prune_instructions(opencode_root: Path) -> int:
    """Remove `.opencode/instruction/` if a legacy v1 mirror is present.

    v1 loaded instruction files through the `instructions` config glob. v2 does
    not resolve that field and reads only `AGENTS.md`, so the mirror is dead
    weight; embed_instructions() inlines the bodies into AGENTS.md instead.
    """
    dst = opencode_root / "instruction"
    if dst.exists():
        shutil.rmtree(dst)
        print("  [PRUNE] instruction/ (v2 loads AGENTS.md — removed)")
        return 1
    print("  [OK] instruction/ absent (v2 reads AGENTS.md)")
    return 0


def embed_instructions(kilo_root: Path, root_dir: Path) -> int:
    """Inline .kilo/instruction/*.md bodies into the root AGENTS.md.

    OpenCode v2 loads only AGENTS.md (global + project, nested on demand); the
    `instructions` config array is accepted but not resolved. The block is
    delimited by markers so regeneration is idempotent and never touches the
    hand-written rulebook around it.
    """
    src_dir = kilo_root / "instruction"
    agents_md = root_dir / "AGENTS.md"
    if not src_dir.is_dir():
        print(f"[ERROR] Source instruction directory not found: {src_dir}")
        return 1
    if not agents_md.is_file():
        print(f"[ERROR] AGENTS.md not found: {agents_md}")
        return 1

    blocks = []
    for f in sorted(src_dir.glob("*.md")):
        body = f.read_text(encoding="utf-8").rstrip()
        blocks.append(f"### {f.name}\n\n{body}")
    section = f"{_AGENTS_MARKER_BEGIN}\n\n" + "\n\n".join(blocks) + f"\n\n{_AGENTS_MARKER_END}"

    text = agents_md.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(_AGENTS_MARKER_BEGIN) + r".*?" + re.escape(_AGENTS_MARKER_END),
        re.DOTALL,
    )
    if pattern.search(text):
        new_text = pattern.sub(lambda _: section, text)
    else:
        new_text = text.rstrip() + "\n\n" + section + "\n"
    _write_if_changed(agents_md, new_text)
    print(f"OpenCode instructions embedded into AGENTS.md: {len(blocks)} file(s)")
    return 0


def generate_opencode_json(
    opencode_root: Path,
    root_dir: Path,
    disabled_skills: dict[str, str] | None = None,
) -> int:
    """Write root opencode.json in the OpenCode v2 schema.

    - `providers.commandcode` is declared in-repo (self-contained) instead of
      relying on the retired v1 plugin `commandcode-go-opencode-provider`. The
      model keys match the harness's existing `commandcode/<id>` references,
      and `modelID` maps back to the upstream Command Code catalog id.
    - `permissions` is v2's ordered array (last match wins) replacing v1's
      `permission` object, using `shell`/`subagent` action names.
    - `instructions` is omitted: v2 does not resolve it; see embed_instructions.

    `disabled_skills` maps skill name -> action for skills whose Kilo/Claude
    frontmatter sets `disable-model-invocation: true`. OpenCode ignores that
    field and has no user-only skill invocation, so the closest faithful
    mapping is `permissions` entries with action `skill` and effect `ask`.
    """
    permissions = [dict(rule) for rule in _BASE_PERMISSION_RULES]
    if disabled_skills:
        # "*" first, specific rules last (v2: last matching rule wins).
        permissions.append({"action": "skill", "resource": "*", "effect": "allow"})
        for name in sorted(disabled_skills):
            permissions.append(
                {"action": "skill", "resource": name, "effect": disabled_skills[name]}
            )

    config: dict[str, Any] = {
        "$schema": "https://opencode.ai/config.json",
        "model": _DEFAULT_MODEL,
        "small_model": _SMALL_MODEL,
        "default_agent": "solo-code-engineer",
        "agents": {"solo-code-engineer": {"model": _DEFAULT_MODEL}},
        "providers": {
            _PROVIDER_ID: {
                "name": "Command Code",
                "env": ["COMMANDCODE_API_KEY"],
                "package": "@opencode/ai/providers/openai-compatible",
                "settings": {"baseURL": "{env:COMMANDCODE_BASE_URL}"},
                "models": _PROVIDER_MODELS,
            }
        },
        "permissions": permissions,
    }
    dst = root_dir / "opencode.json"
    _write_if_changed(dst, json.dumps(config, indent=2) + "\n")
    note = f" ({len(disabled_skills)} skill permission rule(s))" if disabled_skills else ""
    print(f"OpenCode config generated: opencode.json{note}")
    return 0


def generate_all(
    kilo_root: Path, opencode_root: Path, root_dir: Path, *, skip_names: set[str] | None = None
) -> int:
    # skip_names is retained for call-site compatibility; this engine no longer
    # mirrors skills (see prune_duplicate_skills).
    del skip_names
    opencode_root.mkdir(parents=True, exist_ok=True)
    print("--- OpenCode agents ---")
    if generate_agents(kilo_root, opencode_root) != 0:
        return 1
    print("--- OpenCode commands ---")
    generate_commands(kilo_root, opencode_root)
    print("--- OpenCode skills ---")
    prune_duplicate_skills(opencode_root)
    print("--- OpenCode instructions ---")
    prune_instructions(opencode_root)
    embed_instructions(kilo_root, root_dir)
    print("--- OpenCode config ---")
    generate_opencode_json(opencode_root, root_dir, collect_disabled_skills(kilo_root))
    return 0
